CadastroPedidos/ViewModels/PedidoVM.cs
using CadastroPedidos.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CadastroPedidos.ViewModels
{
    public class PedidoVM
    {
        public PedidoVM()
        {
            Itens = new List<Item>();
        }

        public int Id { get; set; }
        [DisplayName("Número")]
        public int Numero { get; set; }
        [DisplayName("Cliente")]
        [Required(ErrorMessage = "Obrigatório informar um Cliente")]
        public int Cliente { get; set; }
        [DisplayName("Data Entrega")]
        [Required(ErrorMessage = "Obrigatório")]
        [DataType(DataType.Date)]
        public DateTime DataEntrega { get; set; }

        [DisplayName("Valor Total")]
        public decimal ValorTotal
        {
            get
            {
                return Itens.Sum(s => s.Valor);
            }
        }
        
        public virtual List<Item> Itens { get; set; }
    }
}

CadastroPedidos/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CadastroPedidos.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

CadastroPedidos/Controllers/PedidoController.cs
using CadastroPedido.Entity.Contracts;
using CadastroPedido.Entity.UoW;
using CadastroPedidos.Models;
using CadastroPedidos.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CadastroPedidos.Controllers
{
    public class PedidoController : Controller
    {
        private IRepositoryPedido _ctx;
        private IRepositoryBase<Cliente> _ctxCliente;
        private IRepositoryBase<Produto> _ctxProduto;
        private IUnitOfWork _UoW;

        public PedidoController(IRepositoryPedido db, IRepositoryBase<Cliente> dbCliente, IUnitOfWork UoW, IRepositoryBase<Produto> ctxProduto)
        {
            _ctx = db;
            _ctxCliente = dbCliente;
            _UoW = UoW;
            _ctxProduto = ctxProduto;
        }

        // GET: Pedido
        public ActionResult Index()
        {
            ViewBag.Clientes = GetClientes();

            return View();
        }

        public ViewResult Pesquisa(int cliente, int numeroPedido, DateTime dataInicial, DateTime dataFinal)
        {
            var resultado = _ctx.Pesquisa(cliente, numeroPedido, dataInicial, dataFinal);

            return View("_Pesquisa", resultado);
        }

        public ViewResult Novo()
        {
            ViewBag.Clientes = GetClientes();
            ViewBag.Produtos = GetProdutos();

            return View();
        }

        public JsonResult Salvar(PedidoVM pedido)
        {
            Pedido model = new Pedido();

            Map(pedido, model);

            _ctx.Create(model);
            _UoW.Commit();

            return Json("{ resultado = true}", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetItem(int IdProduto)
        {
            Produto produto = _ctxProduto.GetById(IdProduto);

            Item item = new Item();
            item.Produto = produto;

            return Json(item, JsonRequestBehavior.AllowGet);
        }

        private List<SelectListItem> GetClientes()
        {
            return _ctxCliente.Get().Select(s => new SelectListItem() { Text = s.Nome, Value = s.Id.ToString() }).ToList();
        }

        private List<SelectListItem> GetProdutos()
        {
            return _ctxProduto.Get().Select(s => new SelectListItem() { Text = s.Descricao, Value = s.Id.ToString() }).ToList();
        }

        private void Map(PedidoVM vm, Pedido model)
        {
            model.ClienteId = vm.Cliente;
            model.DataEntrega = vm.DataEntrega;
            model.Itens = vm.Itens;
        }
    }
}

CadastroPedidos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Apresentação";
}

<div class="jumbotron">
    <h2>Claudevan José da Silva</h2>
    
    <p>Está é uma aplicação de teste, criada para demonstrar meus conhecimentos utilizando tecnologias Microsoft e correlacionadas.</p>

    <h2>Como testar</h2>
    <p>Para testar está aplicação, basta no web.config alterar a ConectionString, 
        com sua configuração de banco de dados e rodar o comando Update-Database no projeto "CadastroPedidos.Entity"</p>
        
    <h2>Tecnologias Utilizadas</h2>
    <ul>
        <li>Code-First</li>
        <li>Repository Pattern</li>
        <li>Injeção de Dependência</li>
        <li>Unity Of Work</li>
        <li>Separação em Camadas (Básico do DDD)</li>
        <li>POO</li>
    </ul>

    <h2>Funcionalidades</h2>
    <ul>
        <li>Cadastro de Pedidos</li>
        <li>Inclusão e Remoção de Itens</li>
    </ul>

    <h2>Funcionalidades Faltantes</h2>
    <ul>
        <li>Pesquisa de Pedidos</li>
        <li>Alteração/Remoção de Pedidos</li>
        <li>Incluir o "https://datatables.net/" para que o grid contivesse paginação e ordenação</li>
        <li>Incluir o Toastr "http://codeseven.github.io/toastr/" para melhorar interação com o usuário</li>
        <li>Incluir o "https://bootstrap-datepicker.readthedocs.io/en/latest/#" para melhor seleção de datas</li>
        <li>Aplicar um style para melhorar a aparência da aplicação</li>
    </ul>
</div>

CadastroPedidos/Views/Pedido/Index.cshtml
@{
    ViewBag.Title = "Consulta Pedido";
}

<h2>Consulta de Pedido</h2>

<form id="formPesquisar">

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            <label for="cliente">Cliente:</label>
            <div>
                @Html.DropDownList("cliente", (List<SelectListItem>)@ViewBag.Clientes, "", new { @class = "form-control", name= "cliente" })
            </div>
        </div>

        <div class="form-group">
            <label for="numero">Número:</label>
            <div>
                <input type="number" id="numero" name="numero" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label for="dataInicial">Data Incial:</label>
            <div>
                <input type="date" id="dataInicial" name="dataInicial" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label for="dataFinal">Data Final:</label>
            <div>
                <input type="date" id="dataFinal" name="dataInicial" class="form-control" />
            </div>
        </div>

        <button id="btnNovo" class="btn btn-success">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            Pesquisar
        </button>
    </div>
</form>

CadastroPedidos/Views/Pedido/Novo.cshtml
@model CadastroPedidos.ViewModels.PedidoVM

<form id="frmNovo">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cadastrar Novo Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.Cliente, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.DropDownListFor(m => m.Cliente, (List<SelectListItem>)@ViewBag.Clientes, "", new { @class = "form-control", name = "Cliente" })
                    @Html.ValidationMessageFor(model => model.Cliente, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.DataEntrega, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.EditorFor(model => model.DataEntrega, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataEntrega, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <h5>Itens do Pedido</h5>
        <div class="row">
            <div class="form-group col-md-6">
                <label for="produto" class="control-label">Produto</label>
                <div>
                    @Html.DropDownList("produto", (List<SelectListItem>)@ViewBag.Produtos, "", new { @class = "form-control", name = "produto" })
                </div>
            </div>

            <div class="form-group col-md-6">
                <button type="button" id="btnAdicionar" class="btn btn-info" onclick="adicionarItem()">Adicionar</button>
            </div>
        </div>

        <div class="form-group">
            <table id="tblProdutos" class="table">
                <thead>
                    <tr>
                        <th style="display:none">Id</th>
                        <th>Produto</th>
                        <th>Quantidade</th>
                        <th>Valor</th>
                        <th>Total</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
 

        <div class="form-group">
            <div>
                <button type="button" value="Salvar" class="btn btn-success" onclick="Salvar()">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                    Salvar
                </button>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @Scripts.Render("~/Scripts/Pedido/Novo.js")
}

CadastroPedidos/Views/Pedido/_Pesquisa.cshtml
@model IEnumerable<CadastroPedidos.Models.Pedido>

<p>
    @Html.ActionLink("Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cliente.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataAlteracao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Numero)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataCadastro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataAlteracao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhe", "Details", new { id=item.Id }) |
            @Html.ActionLink("Remove", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CadastroPedidos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a href="@Url.Action("Index", "Home")" class = "navbar-brand" aria-label="Left Align">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    Purchase
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("Novo", "Pedido")" class="navbar-brand" aria-label="Left Align">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            Novo
                        </a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Claudevan José da Silva</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>